### ISSUE TITLE
Improve UI for Self-Driving Car Project

### ISSUE THREAD

**Issue by anandpanda** [Mohit-Alive/Self-Driving-Car#1]
Great job on the core functionality of the Self-Driving Car project! However, the UI could use some improvements to enhance its appeal and user-friendliness.

![image](https://github.com/user-attachments/assets/d8a5c00f-e26e-4622-91b6-b8f4c6165804)

As you can see, the user interface (UI) could use some improvements to make it more appealing and user-friendly. A polished and attractive UI would greatly enhance the overall experience for users and better showcase the advanced functionalities of the project.

### Add Instructions and Descriptions:
- Provide clear instructions on what the app is doing and how to interact with it.
### Layout and Design:
- Implement a modern and responsive layout using CSS frameworks like Bootstrap or Tailwind CSS.
### Interactivity:
- Improve interactivity with better feedback mechanisms (e.g., hover effects, loading indicators).

These enhancements will make the project more engaging and easier to use. Looking forward to future updates!

**Comment by Mohit-Alive** [comment]
Thanks for the feedback, Anand! I'll work on adding instructions, improving the layout, and enhancing interactivity in the next update. Appreciate the suggestions!
